### ISSUE TITLE
Output of skeleton image resolution is reduced

### ISSUE THREAD

**Issue by ajblanch** [jni/skan#42]
Preview screen size affects output image resolution. Skeleton traces are not visually complete at the current output resolution.

**Comment by jni** [comment]
@ajblanch as a temporary fix, you can jack up the DPI in [this line](https://github.com/jni/skan/blob/3b824524f3c551f716ca810b53a5485a26c519ea/skan/gui.py#L229). 600 should be enough. The real fix, I think, would be to compute the DPI based on the image dimensions and plot dimensions, so that 1 pixel in plot = 1 pixel in image.

**Comment by jni** [comment]
... Or not, that doesn't help. =(

**Comment by jni** [comment]
@ajblanch After further testing, increasing the dpi in that line *should* fix the problem. The question is by how much...

**Comment by jni** [comment]
@ajblanch is this still a problem?

**Comment by ajblanch** [comment]
The output file is presently high enough resolution to view the branches. Though in the present configuration dpi is not defined at all in the line you reference above. [240: self.figure.savefig(output_filename) ].

**Comment by jni** [comment]
Ok I'm just going to assume I set it up correctly somewhere else and close this issue. =) Thanks!

btw feel free to continue to ping me with Skan questions!
